rango/urls.py
from django.conf.urls import url
from django.urls import path
from rango import views


app_name = 'rango'

urlpatterns = [
    path('', views.rango_index, name='index'),
    path('about/', views.about, name='about'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('category/<category_name_slug>/', views.show_category, name='show_category'),
    path('register/', views.register, name='register'),
    path('register_profile/', views.register_profile, name='register_profile'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/<username>', views.user_profile_view, name='profile'),
    path('goto/', views.track_url, name='goto'),
    path('profiles/', views.list_profiles, name='list_profiles'),
    path('like/', views.like_category, name='like_category'),
    path('suggest/', views.suggest_category, name='suggest_category'),
]

tango_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rango import views
from registration.backends.simple.views import RegistrationView


class MyRegistrationView(RegistrationView):
    success_url = 'rango:register_profile'

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
    path('search/', views.search, name='search')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.datetime_safe import datetime


class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0
        super(Category, self).save(*args, **kwargs)

    class Meta:
        # Здесь зададим правильное отображение в множественном числе
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=32)
    url = models.URLField()
    views = models.IntegerField(default=0)
    first_visit = models.DateTimeField(default=datetime.now, blank=True)
    last_visit = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=32, help_text="Enter category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=32, help_text='Enter page title')
    url = forms.URLField(max_length=200, help_text='Enter page url')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from datetime import datetime

import logging
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from registration.forms import User

from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.models import Page, Category, UserProfile

LOGGER = logging.getLogger(__name__)
LOGGER.setLevel(logging.INFO)


def index(request):
    request.session.set_test_cookie()
    return HttpResponse("This is null index <br/><img src=/static/images/3fa.gif> \
                         <br/><a href='/rango/'>Proceed to Rango</a>")


def rango_index(request):
    request.session.set_test_cookie()
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context_dict)
    return response


def about(request):

    visitor_cookie_handler(request)
    context_dict = {'visits': request.session['visits']}
    return render(request, 'rango/about.html', context_dict)


def show_category(request, category_name_slug):
    context_dict = {'category': None, 'pages': None}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['category'] = category
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        pass

    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return rango_index(request)

        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
                profile.save()
                registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    context_dict = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}

    return render(request, 'rango/register.html', context_dict)


def user_login(request):
    context_dict = {}
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                context_dict['disabled_account'] = True
                return render(request, 'rango/login.html', context_dict)

        else:
            print('invalid login details: {0}, {1}'.format(username, password))
            context_dict['bad_details'] = True
            return render(request, 'rango/login.html', context_dict)

    else:
        return render(request, 'rango/login.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits += 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def search(request):
    return render(request, 'rango/search.html')


def track_url(request):
    page_id = None
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
    if page_id:
        try:
            page = Page.objects.get(id=page_id)
            page.views += 1
            page.save()
            return redirect(page.url)
        except Exception:
            return HttpResponse("Page id {0} not found".format(page_id))
    LOGGER.info("No page_id in get string")
    return redirect(reverse('rango:index'))


@login_required
def register_profile(request):
    if request.method == "POST":
        profile_form = UserProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            user_profile = profile_form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()

            return redirect('rango:index')
        else:
            print(profile_form.errors)
    else:
        profile_form = UserProfileForm()

    context_dict = {'form': profile_form}

    return render(request, 'rango/profile_registration.html', context_dict)


@login_required
def user_profile_view(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    LOGGER.critical(userprofile.website)
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', username)
        else:
            print(form.errors)
    return render(request, 'rango/profile.html', {'userprofile': userprofile, 'selecteduser': user, 'form': form})


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html', {'userprofile_list' : userprofile_list})


@login_required
def like_category(request):
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                cat.likes += 1
                likes = cat.likes
                cat.save()
    return HttpResponse(likes)


def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list


def suggest_category(request):
    cat_list = []
    starts_with = ''

    if request.method == 'GET':
        starts_with = request.GET['suggestion']
    cat_list = get_category_list(8, starts_with)
    return render(request, 'rango/categories.html', {'categories': cat_list})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About page
{% endblock %}

{% block body_block %}
    <h1>И начнем мы с..</h1>
    <div>Что это за убожество? Верните мне мои деньги!<br />
        <img src="{% static 'images/about.jpg' %}" alt="картинка из статики"><br />
    </div>
    <div>
        Ты поселил "About" уже <strong>{{ visits }}</strong> раз:)
    </div>
    <div> Здесь поместим картинку из медиа:<br />
        <img src="{{ MEDIA_URL }}stars.jpg">
    </div>
    <p>This is a example</p>
        <button class="btn btn-primary"
            onClick="alert('You clicked the button using JavaScript.');">Click Me - I run JavaScript
        </button>
    <p>This is another example</p>
        <button class="btn btn-primary" id="about-btn">Click Me - I'm JavaScript on Speed</button>
<br/><br/>
<div class="ouch">ouch</div>
    <br/>
<div id="msg">Hello - I'm here for a JQuery Example too</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title_block %}Add new category{% endblock %}

{% block body_block %}
<form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
    <h2 class="form-signin-heading">Add a Category</h2>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
</form>
{% endblock %}



{#{% block body_block %}#}
{##}
{#<form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">#}
{#    <div class="form-group">#}
{#        <h2 class="form-signin-heading"> Add new category</h2>#}
{#        {% csrf_token %}#}
{#        {% for hidden in form.hidden_fields %}#}
{#            {{ hidden }}#}
{#        {% endfor %}#}
{#        {% for field in form.visible_fields %}#}
{#            {{ field.errors }}#}
{#            {{ field.help_text }}#}
{#            {{ field }}#}
{#        {% endfor %}#}
{#    </div>#}
{#    <button class="btn btn-primary" type="submit" name="submit" value="Add category">Add category</button>#}
{#</form>#}
{##}
{#{% endblock %}#}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}Add a new page{% endblock %}

{% block body_block %}

<form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
    <div class="form-group">
    <h2 class="form-signin-heading"> Add a new page to
        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}<br/>
        {{ field }}<br/>
    {% endfor %}
    </div>
    <button class="btn btn-primary" type="submit" name="submit" value="Create page">Add page</button>
</form>
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'images/favicon.ico' %}">
        <title>
            Rango -
            {% block title_block %}
                Whe very best site
            {% endblock %}
        </title>
            <!-- Bootstrap core CSS -->
        <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
        <script type="text/javascript" async="" src="https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js"></script></head>
    </head>

    <body>
        <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
          <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse"
                  data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false"
                  aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <a class="navbar-brand" href="{% url 'rango:index' %}">Home</a>

          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'search' %}">Search</a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:profile' user.username %}">Your profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
              </li>
              {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Registration</a></li>
                {% endif %}
                {% if user.username == 'admin' %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:login' %}">CUSTOM Sign In</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:register' %}">CUSTOM Sign Up</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'rango:logout' %}">CUSTOM Logout</a></li>
                {% endif %}
            </ul>
          </div>
        </nav>
        <div class="container-fluid">
            <nav class="col-sm-3 col-md-2 hidden-xs-down bg-faded sidebar">
              {% block sidebar_block %}
              <ul class="list-group">
                <li class=list-group-item"> Type to find category</li>
                    <form>
                        <li class="list-group-item"><input class="search-query form-control" type="text"
                        name="suggestion" value="" id="suggestion" /></li></form>


                  <div id="cats">
                  </div>
              </ul>
                <hr/>
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'rango:add_category' %}">Add New Category</a>
                {% endif %}
              {% endblock %}
            </nav>


            <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 pt-3">
                {% block body_block %}{% endblock %}
            </div>
        </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.1.1.min.js"crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="http://v4-alpha.getbootstrap.com/assets/js/vendor/jquery.min.js"><\/script>')</script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
        <script src="{% static "js/rango-jquery.js" %}"></script>
        <script src="{% static "js/rango-ajax.js" %}"></script>

    </body>
</html>

templates/rango/categories.html
    {% if categories %}
        {% for category in categories %}
            {% if category == act_category %}
            <li class="list-group-item">><strong><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></strong></li>
            {% else %}
            <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}{{ category.name }}{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
                <button id="likes" data-catid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                Like</button>
            {% endif %}
        </div>
        {% if pages %}
        <ul>
            {% for page in pages %}
                <li><a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                {% if page.views > 1 %}
                    ({{ page.views }} views)
                {% elif page.views == 1 %}
                    ({{ page.views }} view)
                {% endif %}
                </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}
        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add new page to this category</a>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    main page
{% endblock %}

{% block body_block %}
    <div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>

        {% if user.is_authenticated %}
            <h4>Hello, {{ user.username }}</h4>
        {% else %}
            <h4>Hey there, partner!</h4> <br /><br />
        {% endif %}
    </div>
    <div class="row-marketing">
    <section class="row text-center placeholders">
        <div class="col-lg-6">
            <h4>Most liked categories:</h4>
            <p>
            {% if categories %}
                <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item">
                    <a href="{% url 'rango:show_category' category.slug %}"> {{ category.name }}</a>
                </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no categories present.</strong>
        {% endif %}
            </p>
        </div>
        <div class="col-lg-6">
            <h4>Most viewed pages:</h4>
            <p>
            {% if pages %}
            <ul class="list-group">
                {% for page in pages %}
                <li class="list-group-item"><a href="{{ page.url }}"> {{ page.title }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no pages present.</strong>
            {% endif %}
            </p>
        </div>
    </section>
    </div>
    <img src="{% static 'images/owl.jpg' %}" alt="Owl" />
{% endblock %}

templates/rango/list_profiles.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %}User Profiles{% endblock %}
{% block body_block %}
<h1>User Profiles</h1>
    <div class="panel">
        {% if userprofile_list %}
            <div class="panel-heading">
            <!-- Display search results in an ordered list -->
                <div class="panel-body">
                    <div class="list-group">
                    {% for listuser in userprofile_list %}
                        <div class="list-group-item">
                            {% if listuser.picture %}
                            <img width="64" height="64" src="{{ MEDIA_URL }}{{ listuser.picture }}"/>
                            {% else %}
                            <img width="64" height="64" src="{% static 'images/ava_dafault.jpg' %}"/>
                            {% endif %}

                            <h4 class="list-group-item-heading">
                                <a href="{% url 'rango:profile' listuser.user.username %}">{{ listuser.user.username }}</a>
                            </h4>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        {% else %}
            <p>There are no users for the site.</p>
        {% endif %}
    </div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <h1>Login page</h1>
    <form id="login_form" method="post" action="{% url 'rango:login' %}">
        {% if disabled_account %}
            <p><strong>Your account is disabled :(</strong></p>
        {% elif bad_details %}
            <p><strong>Your username and/or password were incorrect!</strong></p>
        {% endif %}

        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" /><br />
        Password: <input type="password" name="password" value="" size="50" /><br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title_block %}Profile{% endblock %}

{% block body_block %}
        <h1>Profile page of user "{{ selecteduser.username }}"</h1>
            <div class="row-marketing">
                <section class="row text-center placeholders">
                    <h4>Your profile details:</h4>
                    <div class="col-lg-12"><ul class="list-group"><li class="list-group-item">
                        {% if userprofile.website %}
                            Website: {{ userprofile.website }}
                        {% else %}
                            no website registered to account
                        {% endif %}
                    </li></ul></div>
                    <div class="col-lg-6">
                        <img src="{{ MEDIA_URL }}{{ userprofile.picture }}" alt="No profile image:(">
                    </div>
                    <div class="col-lg-6">
                        <ul class="list-group">
                            <li class="list-group-item">Username: {{ selecteduser.username }}</li>
                            <li class="list-group-item">Email: {{ selecteduser.email }}</li>
                            <li class="list-group-item">Registry time: {{ selecteduser.date_joined }}</li>
                        </ul>
                    </div>
                </section>
            </div>
    {% if user.username == selecteduser.username  or user.username == 'admin' %}
    <form role="form" id="profile_register_form" method="post" enctype="multipart/form-data"
          action="{% url 'rango:profile' user.username %}">
    <h2 class="form-signin-heading">Edit your profile here</h2>
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit" name="submit">Update profile</button>
</form>
    {% endif %}
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>About Page</h1>
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to homepage</a><br />
    {% else %}
        <strong>Register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
    {% endif %}
{% endblock %}